### ISSUE TITLE
Question regarding usability in bigdata processing framework

### ISSUE THREAD

**Issue by vishnu-chalil** [greenbird/piri#134]
I have been working around this and wanted to know the usability of this library with big data processing framework mainly spark. 
What could be the major challenges in making this usable for apache spark?

**Comment by ChameleonTartu** [comment]
@vishnu-chalil Thx for the question.

I don't see any obvious reason why it wouldn't play well with Apache Spark or any other library/framework.

As we aren't working with Spark ourselves, the library misses appropriate documentation, but we can improve it.

Can you give more examples, use-cases on how you would like to use it?

**Comment by vishnu-chalil** [comment]
@ChameleonTartu What I'am looking at is spark streaming. The job as you probably guessed will be transforming data pulled out of APIs  dumbed to some kafka topic. All the data from kafka topic are going to be pulled to spark, transformed with the configuration file generated according to the usage of this library. Any thoughts on this?

**Comment by ChameleonTartu** [comment]
@vishnu-chalil From a practical perspective, there should be no difference in using `piri` as any other python library. As a secondary solution, you may have an instance of `piri-web` deployed and communicate with data transformer as 3rd party API.

**Comment by vishnu-chalil** [comment]
@ChameleonTartu my only concern would be the performance impact this could have when using in spark.  Would I need to optimize code as by replacing code snipets with pyspark APIs such as for json serializations etc.

**Comment by ChameleonTartu** [comment]
@vishnu-chalil  As we don't have benchmarks, it is hard to say.

The reasons you may move with `piri`:

- It is built on top of [`jsonschema`](https://github.com/Julian/jsonschema) de-facto standard for some IDEs (such as Sublime Text)
- Project backed by `Greenbird` Norwegian company and we are doing integration business
- The project is 100% covered with tests
- If there are any issues with the library, we are open to improving the performance of it

If you are interested in using it, do a proof of concept. Please tell us if the speed is significant so that we can create benchmarks. Based on the feedback, we can profile the solution or make it more pluggable.

**Comment by vishnu-chalil** [comment]
Sure @ChameleonTartu. I will get back with some work done from my side
