### ISSUE TITLE
Add float casting since decimal is not JSON serializable

### ISSUE THREAD

**Issue by dgrald** [greenbird/piri#135]
I'm happy to throw together a pull request for this new casting type, but I just wanted to make sure I'm not missing anything. Thanks!

**Comment by dgrald** [comment]
To clarify, if I try to dump a dictionary that has a decimal casting in it, I receive:
`{TypeError}Object of type Decimal is not JSON serializable`

**Comment by ChameleonTartu** [comment]
Hi @dgrald 

Thank you for asking.

@thomasborgen's answer:
I understand the problem; without a float cast, we can't use the std lib JSON library to dump when working with decimal numbers. However, the reasoning behind it was to make sure we don't lose any precision. Especially if there will be support for adding numbers etc., at a later stage or you are using piri to map data which you then will do a lot of calculations on before dumping.

As a workaround, you can use simplejson or probably any other json serializer/deserializer to dump from Decimal type to normal json float.

My comment:

As decimal serialization is a common issue. [Related Stackoverflow post](https://stackoverflow.com/questions/1960516/python-json-serialize-a-decimal-object). Instead of using `simplejson`, you can subclass from `json.JSONEncoder`, which would be a good solution as well.

**Comment by dgrald** [comment]
Thanks, @ChameleonTartu , that'll work great. I'll go ahead and close the issue.
